services:

    Fastbolt\SonataAdminProtectedFields\EventSubscriber\FormProtectingEventSubscriber:
        tags: [ "kernel.event_subscriber" ]
        arguments:
            $driver: '@Fastbolt\SonataAdminProtectedFields\Mapping\Driver\AttributeDriver'
            $protector: '@Fastbolt\SonataAdminProtectedFields\Protection\DefaultProtector'

    Fastbolt\SonataAdminProtectedFields\Mapping\Driver\AttributeDriver:

    Fastbolt\SonataAdminProtectedFields\Form\FormFieldProvider:

    Fastbolt\SonataAdminProtectedFields\Protection\DefaultProtector:
        arguments:
            $fieldProvider: '@Fastbolt\SonataAdminProtectedFields\Form\FormFieldProvider'

    Fastbolt\SonataAdminProtectedFields\Protection\Checker\PropertyProtectionChecker:
        tags:
            - 'sonata_admin_protected_fields.protection_checkers'

    Fastbolt\SonataAdminProtectedFields\Protection\EntitySecurityHandler\ProtectingSecurityHandler:
        arguments:
            $parent: '@sonata.admin.security.handler.role'
            $driver: '@Fastbolt\SonataAdminProtectedFields\Mapping\Driver\AttributeDriver'
