name: "Psalm PHP checks"

on:
    pull_request:
        paths:
            - "**.php"
            - "psalm.xml"
            - ".psalm/baseline.xml"
            - ".github/workflows/psalm.yaml"
    push:
        paths:
            - "**.php"
            - "psalm.xml"
            - ".psalm/baseline.xml"
            - ".github/workflows/psalm.yaml"

jobs:
    psalm:
        name: Psalm
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@master
            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: '8.0'
            - name: Install dependencies
              run: composer install --prefer-dist --no-progress --no-suggest
              env:
                  COMPOSER_ROOT_VERSION: dev-master
            - name: Run Psalm
              run: ./vendor/bin/psalm --threads=2 --output-format=github --shepherd
